apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: sonarqube-postgres-external-names-exception
  namespace: sonarqube
spec:
  exceptions:
  - policyName: restrict-external-names
    ruleNames:
    - external-names
  match:
    any:
    - resources:
        kinds:
        - Service
        namespaces:
        - sonarqube
        names:
        - sonarqube-postgres
