apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: sonarqube-postgres-registry-exception
  namespace: sonarqube-db
spec:
  exceptions:
  - policyName: restrict-image-registries
    ruleNames:
    - validate-registries
    - autogen-validate-registries
  match:
    any:
    - resources:
        kinds:
        - StatefulSet
        namespaces:
        - sonarqube-db
        names:
        - postgresql
