# Source: bigbang/templates/gitlab/secret-sso.yaml
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-sso-provider
  namespace: gitlab
type: kubernetes.io/opaque
stringData:
  gitlab-sso.json: |-
    {
      "name": "openid_connect",
      "label": "SSO",
      "args": {
        "name": "openid_connect",
        "scope": [
          "Gitlab"
        ],
        "response_type": "code",
        "issuer": "https://keycloak.bigbang.dev/auth/realms/baby-yoda",
        "client_auth_method": "query",
        "discovery": true,
        "uid_field": "preferred_username",
        "client_options": {
          "identifier": "dev_00eb8904-5b88-4c68-ad67-cec0d2e07aa6_gitlab",
          "secret": "",
          "redirect_uri": "https://gitlab.bigbang.dev/users/auth/openid_connect/callback",
          "end_session_endpoint": "https://keycloak.bigbang.dev/auth/realms/baby-yoda/protocol/openid-connect/logout"
        }
      }
    }
