bundle:
  deploy:
    zarf-packages:
      software-factory-idam-gitlab:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      software-factory-idam-realm:
        set:
          DOMAIN: "mtsi.bigbang.dev"
      software-factory-idam-sonarqube:
        set:
          DOMAIN: "mtsi.bigbang.dev"
