replicas: 1
mode: standalone

buckets:
  - name: uds-gitlab-artifacts
  - name: uds-gitlab-backups
  - name: uds-gitlab-ci-secure-files
  - name: uds-gitlab-dependency-proxy
  - name: uds-gitlab-lfs
  - name: uds-gitlab-mr-diffs
  - name: uds-gitlab-packages
  - name: uds-gitlab-pages
  - name: uds-gitlab-terraform-state
  - name: uds-gitlab-uploads
  - name: uds-gitlab-registry
  - name: uds-gitlab-tmp

postJob:
  podAnnotations:
    sidecar.istio.io/inject: "false"
