name: Run E2E Tests

description: Run E2E Tests

inputs:
  token:
    description: Personal Access Token (PAT) used to update the comment
    required: true
  region:
    description: The AWS region to deploy to
    required: true
  role-to-assume:
    description: The AWS IAM Role to assume in the target account
    required: true
  github-context:
    description: The GitHub Status Context to use when updating the status
    required: true
  aws-availability-zone:
    description: The AWS Availability Zone to use
    required: true
  ghcr-username:
    description: The Github container registry username to use
    required: true
  ghcr-password:
    description: The Github container registry password to use
    required: true
  registry1-username:
    description: The Registry1 container registry password to use
    required: true
  registry1-password:
    description: The Registry1 container registry password to use
    required: true

runs:
  using: composite
  steps:
    # Update GitHub status for pending pipeline run
    - name: "Update GitHub Status for pending"
      if: github.event_name == 'repository_dispatch'
      uses: docker://cloudposse/github-status-updater
      with:
        args: "-action update_state -state pending -ref ${{ env.REPO_SHA }} -repo ${{ env.REPO_NAME }}"
      env:
        REPO_SHA: ${{ github.event.client_payload.pull_request.head.sha || github.sha }}
        REPO_NAME: ${{ github.event.client_payload.github.payload.repository.name || github.event.repository.name }}
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_CONTEXT: ${{ inputs.github-context }}
        GITHUB_DESCRIPTION: "started by @${{ github.event.client_payload.github.actor || github.actor }}"
        GITHUB_TARGET_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        GITHUB_REF: ${{ github.event.client_payload.pull_request.head.ref || github.ref_name }}
        GITHUB_OWNER: ${{ github.event.client_payload.github.payload.repository.owner.login || github.repository_owner }}

    - name: Init gopath cache
      uses: actions/cache@v3
      with:
        path: "${{ github.workspace }}/.cache/go"
        key: "gopath|${{ hashFiles('.tool-versions') }}|${{ hashFiles('go.sum') }}"

    - name: Init gobuild cache
      uses: actions/cache@v3
      with:
        path: "${{ github.workspace }}/.cache/go-build"
        key: "gobuild|${{ hashFiles('.tool-versions') }}|${{ hashFiles('go.sum') }}"

    - name: Init zarf cache
      uses: actions/cache@v3
      with:
        path: "${{ github.workspace }}/.cache/.zarf-cache"
        key: "zarf|${{ hashFiles('.tool-versions') }}"

    - name: Init docker cache
      id: init-docker-cache
      uses: actions/cache@v3
      with:
        path: "${{ github.workspace }}/.cache/docker"
        key: "docker|${{ hashFiles('.env') }}"

    - name: Docker save build harness
      if: steps.init-docker-cache.outputs.cache-hit != 'true'
      shell: bash -e -o pipefail {0}
      run: |
        make docker-save-build-harness

    - name: Load build harness
      shell: bash -e -o pipefail {0}
      run: |
        make docker-load-build-harness

    - name: Get Terraform version from .tool-versions
      id: get_tf_version
      shell: bash -e -o pipefail {0}
      run: echo "tf_version=$(grep 'terraform ' .tool-versions)" >> $GITHUB_OUTPUT

    - name: Configure AWS Credentials for Commercial
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        role-session-name: ${{ github.event.client_payload.pull_request.head.sha || github.sha }}
        aws-region: ${{ inputs.region }}
        # 21600 seconds == 6 hours
        role-duration-seconds: 21600

    - name: "Run E2E tests"
      shell: bash -e -o pipefail {0}
      env:
        AWS_AVAILABILITY_ZONE: ${{ inputs.aws-availability-zone }}
        AWS_DEFAULT_REGION: us-east-2
        REGISTRY1_USERNAME: ${{ inputs.registry1-username }}
        REGISTRY1_PASSWORD: ${{ inputs.registry1-password }}
        GHCR_USERNAME: ${{ inputs.ghcr-username }}
        GHCR_PASSWORD: ${{ inputs.ghcr-password }}
        REPO_URL: https://github.com/${{ github.repository }}.git
        GIT_BRANCH: ${{ github.event.client_payload.pull_request.head.ref || github.ref_name }}
      run: |
        make test fix-cache-permissions

    # Update GitHub status for successful pipeline run
    - name: "Update GitHub Status for success"
      if: ${{ success() && github.event_name == 'repository_dispatch' }}
      uses: docker://cloudposse/github-status-updater
      with:
        args: "-action update_state -state success -ref ${{ env.REPO_SHA }} -repo ${{ env.REPO_NAME }}"
      env:
        REPO_SHA: ${{ github.event.client_payload.pull_request.head.sha || github.sha }}
        REPO_NAME: ${{ github.event.client_payload.github.payload.repository.name || github.event.repository.name }}
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_CONTEXT: ${{ inputs.github-context }}
        GITHUB_DESCRIPTION: "run passed"
        GITHUB_TARGET_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        GITHUB_REF: ${{ github.event.client_payload.pull_request.head.ref || github.ref_name }}
        GITHUB_OWNER: ${{ github.event.client_payload.github.payload.repository.owner.login || github.repository_owner }}

    # Update GitHub status for failing pipeline run
    - name: "Update GitHub Status for failure"
      if: ${{ failure() && github.event_name == 'repository_dispatch' }}
      uses: docker://cloudposse/github-status-updater
      with:
        args: "-action update_state -state failure -ref ${{ env.REPO_SHA }} -repo ${{ env.REPO_NAME }}"
      env:
        REPO_SHA: ${{ github.event.client_payload.pull_request.head.sha || github.sha }}
        REPO_NAME: ${{ github.event.client_payload.github.payload.repository.name || github.event.repository.name }}
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_CONTEXT: ${{ inputs.github-context }}
        GITHUB_DESCRIPTION: "run failed"
        GITHUB_TARGET_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        GITHUB_REF: ${{ github.event.client_payload.pull_request.head.ref || github.ref_name }}
        GITHUB_OWNER: ${{ github.event.client_payload.github.payload.repository.owner.login || github.repository_owner }}

    # Update GitHub status for cancelled pipeline run
    - name: "Update GitHub Status for cancelled"
      if: ${{ cancelled() && github.event_name == 'repository_dispatch' }}
      uses: docker://cloudposse/github-status-updater
      with:
        args: "-action update_state -state error -ref ${{ env.REPO_SHA }} -repo ${{ env.REPO_NAME }}"
      env:
        REPO_SHA: ${{ github.event.client_payload.pull_request.head.sha || github.sha }}
        REPO_NAME: ${{ github.event.client_payload.github.payload.repository.name || github.event.repository.name }}
        GITHUB_TOKEN: ${{ inputs.token }}
        GITHUB_CONTEXT: ${{ inputs.github-context }}
        GITHUB_DESCRIPTION: "run cancelled"
        GITHUB_TARGET_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        GITHUB_REF: ${{ github.event.client_payload.pull_request.head.ref || github.ref_name }}
        GITHUB_OWNER: ${{ github.event.client_payload.github.payload.repository.owner.login || github.repository_owner }}
