name: build-and-publish

concurrency:
    cancel-in-progress: true
    group: build-and-publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-publish-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - uses: actions/checkout@v3
        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')

      - name: Init zarf cache
        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
        uses: actions/cache@v3
        with:
          path: "~/.zarf-cache"
          key: zarf-cache

      - name: Free GH runner build space
        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
        run: |
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          df -h

      - name: Install zarf
        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
        uses: supplypike/setup-bin@v3
        with:
          # renovate: zarf-uri datasource=github-tags depName=defenseunicorns/zarf
          uri: 'https://github.com/defenseunicorns/zarf/releases/download/v0.29.1/zarf_v0.29.1_Linux_amd64'
          name: 'zarf'
          # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
          version: 'v0.29.1'

      - name: Install uds-cli
        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
        uses: supplypike/setup-bin@v3
        with:
          # renovate: uds-cli-uri datasource=github-tags depName=defenseunicorns/uds-cli
          uri: 'https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.4-alpha/uds-cli_v0.0.4-alpha_Linux_amd64 '
          name: 'uds'
          # renovate: datasource=github-tags depName=defenseunicorns/uds-cli versioning=semver
          version: 'v0.0.4-alpha'

      - name: Login to GHCR
        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to registry1
        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
        uses: docker/login-action@v2
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}

      - name: Build Software Factory Dependencies Packages
        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
        run: |
          mkdir -p build
          zarf package create packages/idam-dns       --confirm --no-progress --output-directory build
          zarf package create packages/idam-gitlab    --confirm --no-progress --output-directory build
          zarf package create packages/idam-sonarqube --confirm --no-progress --output-directory build
          zarf package create packages/idam-realm     --confirm --no-progress --output-directory build
          zarf package create packages/namespaces     --confirm --no-progress --output-directory build

      - name: Build software factory bundle
        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
        run: uds bundle create --confirm --no-progress

      - name: Publish software factory bundle
        if: contains(steps.changed-files.outputs.modified_files, 'uds-bundle.yaml')
        run: uds bundle publish uds-bundle-software-factory-demo-amd64-*.tar.zst oci://ghcr.io/defenseunicorns/uds-package --no-progress
