name: test-new-ci

permissions:
  id-token: write
  contents: read
  packages: write

defaults:
  run:
    # We need -e -o pipefail for consistency with GitHub Actions' default behavior
    shell: bash -e -o pipefail {0}

on:
  push:
  workflow_dispatch:

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create k3s cluster in AWS
        id: create-cluster
        uses: defenseunicorns/uds-aws-ci-k3d@swf_additions
        with:
          cluster-action: create
          aws-assume-role: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME_K3D }}
          aws-region: us-west-2
          instance-size: "m7a.8xlarge"
          ami-prefix: "rc-uds-ci-k3d"
          k3s: "true"

      - name: Upload kubeconfig artifact
        uses: actions/upload-artifact@v3
        with: 
          name: kubeconfig
          path: ~/.kube/config

      - name: Install Pepr lb module
        run: |
          kubectl apply -f test/lb-annotation-aws/pepr-module-lb-annotate.yaml

      - name: Install Pepr flux resources module
        run: |
          kubectl apply -f test/flux-resources-bump/pepr-module-flux-resources.yaml

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to registry1
        uses: docker/login-action@v2
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build bundle and all dependencies
        run: |
          make build/all

  deploy:
    runs-on: ubuntu-latest
    needs: ["create-cluster", "build"]
    steps:
      - name: Allow access to cluster
        id: create-cluster
        uses: defenseunicorns/uds-aws-ci-k3d@swf_additions
        with:
          cluster-action: create
          aws-assume-role: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME_K3D }}
          aws-region: us-west-2
          instance-size: "m7a.8xlarge"
          ami-prefix: "rc-uds-ci-k3d"
          k3s: "true"

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download kubeconfig
        uses: actions/download-artifact@v3
        with:
          name: kubeconfig
          path: ~/.kube/

      - name: Download zarf and uds-cli
        run: |
          make build/zarf
          make build/uds

      - name: Move Zarf to /usr/local/bin
        run: |
          sudo mv build/zarf /usr/local/bin/zarf
          sudo chmod +x /usr/local/bin/zarf

      - name: Deploy bundle
        run: |
          make deploy

  test:
    runs-on: ubuntu-latest
    needs: "deploy"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Allow access to cluster
        id: create-cluster
        uses: defenseunicorns/uds-aws-ci-k3d@swf_additions
        with:
          cluster-action: create
          aws-assume-role: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME_K3D }}
          aws-region: us-west-2
          instance-size: "m7a.8xlarge"
          ami-prefix: "rc-uds-ci-k3d"
          k3s: "true"

      - name: Download kubeconfig
        uses: actions/download-artifact@v3
        with:
          name: kubeconfig
          path: ~/.kube/

      - name: Setup LB hostnames
        run: |
          utils/metallb/dns.sh
          echo "hosts patch:"
          cat hosts.patch
          echo "hosts file before:"
          cat /etc/hosts
          sudo utils/metallb/hosts-write.sh
          echo "hosts file after:"
          cat /etc/hosts

      - name: Run tests
        run: |
          kubectl rollout status deployment/gitlab-webservice-default -n gitlab --watch --timeout=1200s
          curl https://keycloak.bigbang.dev
          curl https://gitlab.bigbang.dev
          curl https://grafana.bigbang.dev

  debug-cluster:
    runs-on: ubuntu-latest
    needs: "test"
    if: failure()
    steps:
      - name: Allow access to cluster
        id: create-cluster
        uses: defenseunicorns/uds-aws-ci-k3d@swf_additions
        with:
          cluster-action: create
          aws-assume-role: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME_K3D }}
          aws-region: us-west-2
          instance-size: "m7a.8xlarge"
          ami-prefix: "rc-uds-ci-k3d"
          k3s: "true"

      - name: Download kubeconfig
        uses: actions/download-artifact@v3
        with:
          name: kubeconfig
          path: ~/.kube/

      - name: Print cluster info
        run: |
          kubectl get nodes -o wide
      
      - name: Print pod info
        run: |
          kubectl get pods -A -o wide

      - name: Print service info
        run: |
          kubectl get svc -A -o wide

      - name: Print events
        run: |
          kubectl get events -A -o wide

  teardown-cluster:
    runs-on: ubuntu-latest
    needs: ["test", "debug-cluster"]
    if: always()
    steps:
      - name: Teardown k3s cluster
        if: always()
        # renovate: datasource=github-tags depName=defenseunicorns/uds-aws-ci-k3d versioning=semver
        uses: defenseunicorns/uds-aws-ci-k3d@swf_additions
        with:
          cluster-action: destroy